server:
  port: 5880

spring:
  application:
    name: sms-user-management-service
  datasource:
    url: jdbc:mysql://localhost:3306/sms
    username: root
    password: Sevitha@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org.mybatis: DEBUG